name: hello_assembly
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.0-266.8.beta <3.0.0'

dependencies:
  ffi: 2.0.0

dev_dependencies:
  extra_pedantic: ^2.0.0
  test: ^1.16.0
